{% set version = "1.0" %}
{% set name = "pyminer" %}


package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python 3.9.1
    - pip
    - nodejs
    - beautifulsoup4 4.9
    - bs4 4.9.3
    - click 7.1.2
    - pandas 1.2.1
  run:
    - python

about:
  home: https://github.com/J-E-J-S/journal-miner
  license: MIT
  summary: Python CLI for mining scientific literature.
  description: |
    This package contains a CLI that allows mining of the EUPMC database for
    papers that contain hits for keywords.
